const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = 3000;

app.use(cors());
app.use(express.static('public'));

// Serve the Mangalore Map HTML generated by Python
app.get('/map', (req, res) => {
    res.sendFile(path.join(__dirname, '../mangalore_flood_routing.html'));
});

// Serve the live statistics generated by Python pipeline
app.get('/live-stats', (req, res) => {
    res.sendFile(path.join(__dirname, '../live_stats.json'));
});

app.use(express.json()); // Add JSON parser

// Trigger Python Pipeline (Optional for future, but good to have)
app.post('/run-pipeline', (req, res) => {
    const { exec } = require('child_process');
    const { mode, amb_count, ambulances } = req.body || {};

    let cmd = `python main.py --amb_count ${amb_count || 2}`;

    if (mode === 'custom' && ambulances && ambulances.length > 0) {
        ambulances.forEach((amb, i) => {
            cmd += ` --amb${i+1} ${amb.start_lat},${amb.start_lon},${amb.end_lat},${amb.end_lon}`;
        });
    }

    exec(cmd, { cwd: path.join(__dirname, '..') }, (error, stdout, stderr) => {
        if (error) {
            console.error(`exec error: ${error}`);
            return res.status(500).json({ status: 'error', message: error.message });
        }
        res.json({ status: 'success', output: stdout });
    });
});

app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
