"""Set the trimmed main manuscript in two-column IEEE format.

Motivation, from measurement rather than preference. After removing the genuinely
redundant floats, the single-column manuscript sits at 25 pages: 6704 words of
prose and 27 floats. Reaching 20 pages in one column would require each float to
occupy about 0.14 of a page, roughly 4 cm including its caption, which is not
achievable for a multi-panel map or a ten-row table. The remaining single-column
routes to 20 pages are cutting ~40% of the prose or dropping ~10 floats, both of
which discard evidence.

Two columns fit the same content into the target length: the measure halves, so
charts and narrow tables cost proportionally less page area, and body text sets
at roughly twice the words per page.

Reuses the conversion machinery written for the split papers, which handles the
things that break silently when a one-column document becomes two-column.

Reads  paper/main/main_paper.tex
Writes paper/main/main_paper_2col.tex
"""
import os
import re
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
import split_journal as sj  # noqa: E402

SRC = "paper/main/main_paper.tex"
DST = "paper/main/main_paper_2col.tex"

PREAMBLE = r"""%%=============================================================================
%%  Main manuscript, two-column IEEE format.
%%
%%  Build:  tectonic main_paper_2col.tex
%%
%%  Generated by scripts/main_twocolumn.py from main_paper.tex, which is itself
%%  generated from paper/paper_journal_v2.tex by scripts/trim_main.py. Edit the
%%  source manuscript and re-run both, not this file.
%%=============================================================================
\documentclass[journal]{IEEEtran}

\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{array}
\usepackage{xcolor}
\usepackage{tikz}
\usetikzlibrary{positioning,arrows.meta,fit,backgrounds}
\usepackage{caption}
\usepackage{subcaption}
\captionsetup[sub]{font=small}
\usepackage[numbers,sort&compress]{natbib}
\usepackage[hidelinks]{hyperref}
\usepackage{siunitx}
\sisetup{detect-all,group-separator={,}}
\usepackage{balance}

\renewcommand{\arraystretch}{1.05}

\newcommand{\Sx}{S(\mathbf{x})}
\newcommand{\Tt}{T(t)}
\newcommand{\Rxt}{R(\mathbf{x},t)}

\begin{document}

\title{Spatiotemporal Flood Risk Modelling Under a Single-Orbit SAR Constraint:
Confound-Controlled Susceptibility, Flood-Aware Routing and Hybrid Quantum
Dispatch}

%% Author identities removed for anonymous review. Restore before camera-ready.
\author{}

\maketitle

"""


def main():
    s = open(SRC, encoding="utf-8").read()

    head, rest = s.split(r"\begin{thebibliography}", 1)
    opts, bibbody = rest.split("\n", 1)
    bibbody, _ = bibbody.split(r"\end{thebibliography}", 1)

    body = head.split(r"\maketitle", 1)[1]

    # keep the abstract, but as IEEEtran's environment plus keywords
    m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", body, re.S)
    abstract = m.group(1).strip()
    body = body[:m.start()] + body[m.end():]

    # The article-class abstract ends with an inline "Keywords:" line. IEEEtran
    # has its own IEEEkeywords block, so the inline one must go or both print.
    keywords = ("Flood susceptibility, synthetic aperture radar, spatial "
                "cross-validation, explainable AI, flood-aware routing, "
                "emergency dispatch, QUBO, QAOA.")
    kw = re.search(r"\\noindent\\textbf\{Keywords:\}.*?(?=\\end\{abstract\}|\Z)",
                   abstract + "\\end{abstract}", re.S)
    if kw:
        abstract = abstract[:kw.start()].rstrip()
    if "Keywords:" in abstract:
        raise SystemExit("inline keywords line still present in the abstract")

    body = sj.fix_widths(body)
    body = sj.fix_wide_math(body)
    body = sj.fix_paragraph_headings(body)
    body = sj.shrink_tables(body)
    body = sj.widen(body)

    doc = (PREAMBLE
           + "\\begin{abstract}\n" + abstract + "\n\\end{abstract}\n\n"
           + "\\begin{IEEEkeywords}\n" + keywords + "\n\\end{IEEEkeywords}\n"
           + body
           + "\n\\balance\n\\begin{thebibliography}{99}\n"
           + bibbody
           + "\\end{thebibliography}\n\n\\end{document}\n")

    open(DST, "w", encoding="utf-8").write(doc)
    nfig = len(re.findall(r"\\begin\{figure", doc))
    ntab = len(re.findall(r"\\begin\{table", doc))
    nref = doc.count("\\bibitem")
    print(f">> wrote {DST}: {nfig} figures, {ntab} tables, {nref} references")


if __name__ == "__main__":
    main()
