// Loads the REAL exported model assets from /public/data (generated by
// scripts/export_web_assets.py). Replaces the synthetic geoData.js generators.
// Everything here is genuine: SAR-trained susceptibility raster, the real OSM
// road network with per-edge risk, and the real flood-aware / risk-blind routes.

const base = "/data";

async function getJSON(path) {
  const r = await fetch(`${base}/${path}`);
  if (!r.ok) throw new Error(`failed to load ${path}: ${r.status}`);
  return r.json();
}

// Susceptibility raster (turbo-colormapped PNG) + geographic corners for a
// Mapbox `image` source, which drapes natively onto 3D terrain.
export async function loadOverlay() {
  const b = await getJSON("susceptibility_overlay.bounds.json");
  return {
    url: `${base}/susceptibility_overlay.png`,
    // Mapbox image source wants [TL, TR, BR, BL]
    coordinates: b.coordinates,
    bbox: b.bbox,
  };
}

export const loadRoads = () => getJSON("roads_light.geojson"); // 30,000 representative edges
export const loadRoutes = (id) => getJSON(`routes_${id}.geojson`);
export const loadBlocked = (id) => getJSON(`blocked_${id}.geojson`);
export const loadDispatch = () => getJSON("dispatch.json");
export const loadManifest = () => getJSON("manifest.json");

// Split a routes FeatureCollection into blind/aware and index by hospital→incident.
export function splitRoutes(fc) {
  const out = { blind: [], aware: [], byPair: {} };
  for (const f of fc.features) {
    const p = f.properties;
    out[p.kind]?.push(f);
    (out.byPair[`${p.hospital}_${p.incident}`] ||= {})[p.kind] = f;
  }
  return out;
}

// Sample a coordinate path at normalized t (0..1) by cumulative segment length.
export function positionAlong(coords, t) {
  if (t <= 0) return coords[0];
  if (t >= 1) return coords[coords.length - 1];
  const seglen = [];
  let total = 0;
  for (let i = 1; i < coords.length; i++) {
    const d = Math.hypot(coords[i][0] - coords[i - 1][0], coords[i][1] - coords[i - 1][1]);
    seglen.push(d); total += d;
  }
  let target = t * total, acc = 0;
  for (let i = 0; i < seglen.length; i++) {
    if (acc + seglen[i] >= target) {
      const lt = (target - acc) / (seglen[i] || 1e-9);
      return [
        coords[i][0] + (coords[i + 1][0] - coords[i][0]) * lt,
        coords[i][1] + (coords[i + 1][1] - coords[i][1]) * lt,
      ];
    }
    acc += seglen[i];
  }
  return coords[coords.length - 1];
}
